### ISSUE TITLE
Add assertions that only log messages on failure

### ISSUE THREAD

**Issue by bmblb** [bryntum/siesta#11] opened 2021-05-25 21:04 UTC
Usecase: common assertions that are useful but leave too many messages in the test log.
Proposal: 
```
foo = true;
bar = false;
t.optFail.ok(foo, 'Foo is ok') // doesn't log anything
t.optFail.ok(bar, 'Bar is ok') // logs 'bar is not ok'
```

It could be handy to make this a modifier for regular assertion, much like `.not.`

**Comment by canonic-epicure** [comment] 2021-05-26 07:10
Duplicate of https://github.com/bryntum/siesta/issues/2

**Comment by canonic-epicure** [comment] 2021-05-26 07:15
I'm inclining more to the lambda wrapper as in #2 instead of the `optFail` magic property.

**Closed** 2021-05-26 07:49 UTC

**Comment by bmblb** [comment] 2021-05-26 07:51
@canonic-epicure this property is not more magic than `.not.`, it is merely a modifier for the assertion behavior. I do not insist on the name if it makes any difference. maybe `t.silent.is` would gain more approval
